#
# Site settings
#
title: 昨日のイナーシャ
email: rawkranz@gmail.com
description: >
    昨日の記録。またそこに行きやすいように。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sousu.jp" # the base hostname & protocol for your site
twitter_username: sou_su
github_username:  sousu

# Build settings
markdown: kramdown
exclude: ['Rakefile','README.md','config.rb','Gemfile','Gemfile.lock','vender']

timezone: Asia/Tokyo
markdown_ext: "md,txt"

